[package]
name = "procon2021_comp"
version = "0.1.0"
authors = ["combnitnc"]
edition = "2018"
default-run = "procon2021_comp"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.40"
easy-parallel = "3.1.0"
image = "0.23.14"
png = "0.17.0"
reqwest = { version = "0.11.4", features = ["blocking"] }

[dev-dependencies]
rand = "0.8.4"

[profile.release]
codegen-units = 1
lto = "fat"
