name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Setup SDL2
        run: |
         sudo apt update
         sudo apt install libsdl2-dev libsdl2-ttf-dev
      - name: Build
        run: cargo build --release --verbose
      - name: Run tests
        run: cargo test --release --verbose

  clippy_check:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Setup SDL2
        run: |
         sudo apt update
         sudo apt install libsdl2-dev libsdl2-ttf-dev
      - run: rustup component add clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
